server:
  applicationConnectors:
    - type: http
      port: 3000
  #    - type: https
  #      port: 3443
  #      keyStorePath: example.keystore
  #      keyStorePassword: example
  adminConnectors:
    - type: http
      port: 3001
#    - type: https
#      port: 3444
#      keyStorePath: example.keystore
#      keyStorePassword: example

logging:
  #Logger can take values: OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  #INFO is default level of all loggers.
  level: INFO

question: "What should I call you?"

greetingTemplate: "Hello, %s!!"